name: Guardião do Grimório - Keep Alive

on:
  schedule:
    - cron: '0 0 */5 * *' # Executa a cada 5 dias à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Invocando o Banco de Dados de Oregon
        run: |
          curl -X GET "https://rbygxkbewzknvjjhxdvw.supabase.co/rest/v1/grimorio_prompts?select=*" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieWd4a2Jld3prbnZqamh4ZHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMDcxNjQsImV4cCI6MjA4MTU4MzE2NH0.YrHF9HEGo6yv9MyNsPzFgBhaAB1DRh2SLU8f7L6s1nY" \
          -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieWd4a2Jld3prbnZqamh4ZHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwMDcxNjQsImV4cCI6MjA4MTU4MzE2NH0.YrHF9HEGo6yv9MyNsPzFgBhaAB1DRh2SLU8f7L6s1nY"
